export const chocklate = [
    {
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/Stunning%20Flower%20Arrangement.jpg",
        rating : "8.9",
        price : "149",
        favourite :false,
        cart : false,
    },{
        title : 'Munch Chocolate',
        image : "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/parle-chocolates.jpg",
        rating : "8.9",
        price : "159",
        favourite :false,
        cart : false,
    },{
        title : ' Ferrero Rocher Chocolates',
        image : "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/ferrero-rocher-chocolates.jpg",
        rating : "8.9",
        price : "169",
        favourite :false,
        cart : false,
    },{
        title : 'Floweraura',
        image : "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/lotus-chocolates.jpg",
        rating : "8.9",
        price : "169",
        favourite :false,
        cart : false,
    },{
        title : 'Pacari Chocolates',
        image : "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/pacari-chocolates.jpg",
        rating : "8.9",
        price : "249",
        favourite :false,
        cart : false,
    },{
        title : 'fabelle-chocolate',
        image : "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/fabelle-chocolate.jpg",
        rating : "8.9",
        price : "349",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/cover_228.jpg",
        rating : "8.9",
        price : "449",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/Stunning%20Flower%20Arrangement.jpg",
        rating : "8.9",
        price : "549",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/cover_228.jpg",
        rating : "8.9",
        price : "149",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/cover_228.jpg",
        rating : "8.9",
        price : "649",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/Stunning%20Flower%20Arrangement.jpg",
        rating : "8.9",
        price : "649",
        favourite :false,
        cart : false,
    },{
        title : 'xyz choclate',
        image : "https://imgcdn.floweraura.com/plum-cake-recipe.jpg",
        rating : "8.9",
        price : "149",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/Stunning%20Flower%20Arrangement.jpg",
        rating : "8.9",
        price : "749",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/cover_231.jpg",
        rating : "8.9",
        price : "849",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/cover_231.jpg",
        rating : "8.9",
        price : "949",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/plum-cake-recipe.jpg",
        rating : "8.9",
        price : "49",
        favourite :false,
        cart : false,
    },{
        title : 'Dairy Milk',
        image : "https://imgcdn.floweraura.com/cover_231.jpg",
        rating : "8.9",
        price : "19",
        favourite :false,
        cart : false,
    }
]